name: PR Checks

on:
  pull_request:
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest

    env:
      PUBLIC_SUPABASE_URL: ${{ vars.PUBLIC_SUPABASE_URL }}
      PUBLIC_SUPABASE_ANON_KEY: ${{ vars.PUBLIC_SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      DASHBOARD_PROJECT_ID_VERCEL: ${{ secrets.DASHBOARD_PROJECT_ID_VERCEL }}
      TEAM_ID_VERCEL: ${{ secrets.TEAM_ID_VERCEL }}
      AUTH_BEARER_TOKEN: ${{ secrets.AUTH_BEARER_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.5.0
      - run: npm ci
      - run: npm run build
      - run: npm run lint
